[#50] feat: run application 위한 bash script 작성
- application-prod.yml 설정 내용 일부 삭제(spring.config.import)
- service.sh.j2 내용 작성(단순 중단 배포 방식)

diff --git a/scripts/deploy/playbook/templates/service.sh.j2 b/scripts/deploy/playbook/templates/service.sh.j2
--- a/scripts/deploy/playbook/templates/service.sh.j2
+++ b/scripts/deploy/playbook/templates/service.sh.j2
@@ -1,3 +1,42 @@
 #!/bin/bash
 
 ENV_LOCATION={{ remote_env_path }}
+APP_WORKSPACE = {{ remote_app_path }}
+MODULE_NAME={{ module_name }}
+PORT=8080
+
+SPRING_PROFILE={{ spring_profile }}
+
+PID_FILE=${APP_WORKSPACE}/${MODULE_NAME}_${PORT}.pid
+STD_OUT=${APP_WORKSPACE}/logs/stdout_${PORT}.log
+STD_ERROR=${APP_WORKSPACE}/logs/stderr_${PORT}.log
+
+echo "## 0. export env file path"
+export ENV_LOCATION
+
+echo "## 1. move to application workspace"
+cd $APP_WORKSPACE
+
+echo "## 2. move to application workspace"
+CURRENT_PID = $(pgrep -f ${MODULE_NAME})
+
+if [ -z "${CURRENT_PID}" ];
+then
+  echo "no current running application >> pass killing process"
+else
+  echo "kill -TERM CURRENT_PID"
+  kill -TERM ${CURRENT_PID}
+fi
+
+echo "## 3. run application"
+java --version
+if [ $? -ne 0 ];
+then
+  echo "no JRE setup > JRE is required!!"
+  exit 1
+fi
+
+nohup java -jar \
+  -Dspring.config.import=optional:file:${ENV_LOCATION}/.env[.properties] \
+  -Dspring.profiles.active=${SPRING_PROFILE} \
+  ${APP_WORKSPACE}/${MODULE_NAME}.jar 1>${STD_OUT} 2>$1 &
