[#64] ci: health check 부분 잘못된 구문 수정

diff --git a/scripts/deploy/roles/run-app/templates/service.sh.j2 b/scripts/deploy/roles/run-app/templates/service.sh.j2
--- a/scripts/deploy/roles/run-app/templates/service.sh.j2
+++ b/scripts/deploy/roles/run-app/templates/service.sh.j2
@@ -21,29 +21,7 @@ SPRING_PROFILE="{{ spring_profile }}"
 STD_OUT=${APP_WORKSPACE}/logs/stdout_${PORT}.log
 STD_ERR=${APP_WORKSPACE}/logs/stderr_${PORT}.log
 
-# health check application
-CHECK_MAX_COUNT=10
-CHECK_COUNT=0
-func_app_health_check() {
-  echo ">> application(${PORT}) health check"
-  if [ $CHECK_COUNT -gt $CHECK_MAX_COUNT ];
-  then
-    echo "Failure of running java application(${PORT})"
-    exit 50
-  fi
-
-  status_code=$(curl --connect-timeout 1 --max-time 3 -i -X GET http://localhost:"${PORT}"/health | awk '/HTTP\/1/{print $2}')
-  if [[ $status_code =~ ^2[0-9]{2}$ ]];
-  then
-    echo "application(${PORT}) health check > UP"
-  else
-    echo "application(${PORT}) health check > DOWN"
-    sleep 3
-    CHECK_COUNT=$(expr ${CHECK_COUNT} + 1)
-    app_health_check
-  fi
-}
-
+# toggle proxy upstream status (up, down)
 func_toggle_proxy_upstream() {
   local toggle_status
   toggle_status=$1
@@ -86,6 +64,28 @@ func_toggle_proxy_upstream() {
   sudo systemctl reload nginx
 }
 
+# health check application
+CHECK_MAX_COUNT=10
+CHECK_COUNT=0
+func_app_health_check() {
+  if [ $CHECK_COUNT -gt $CHECK_MAX_COUNT ];
+  then
+    echo "Failure of running java application(${PORT})"
+    exit 50
+  fi
+
+  status_code=$(curl --connect-timeout 1 --max-time 3 -i -X GET http://localhost:"${PORT}"/health | awk '/HTTP\/1/{print $2}')
+  if [[ $status_code =~ ^2[0-9]{2}$ ]];
+  then
+    echo "application(${PORT}) health check > UP"
+  else
+    echo "application(${PORT}) health check > DOWN"
+    sleep 3
+    CHECK_COUNT=$(expr ${CHECK_COUNT} + 1)
+    func_app_health_check
+  fi
+}
+
 # shutdown application
 shutdown() {
   echo "-----------------------------------------"
@@ -126,6 +126,7 @@ run_app() {
     -Dserver.port="${PORT}" \
     "${APP_WORKSPACE}"/"${MODULE_NAME}".jar 1>"${STD_OUT}" 2>"${STD_ERR}" &
 
+  echo ">> application(${PORT}) health check"
   func_app_health_check
 
   func_toggle_proxy_upstream up
